<?php
// generated by Poedit from rsfirewall-en.po, do not edit directly 
return ['domain'=>NULL,'plural-forms'=>'nplurals=2; plural=(n != 1);','language'=>'en','pot-creation-date'=>'2025-04-11 14:42+0300','po-revision-date'=>'2025-04-11 14:42+0300','translation-revision-date'=>'2025-04-11 14:42+0300','project-id-version'=>'RSFirewall!','x-generator'=>'Poedit 3.6','messages'=>[]];
