<?php
// generated by Poedit from rsfirewall-en.po, do not edit directly
return ['domain'=>NULL,'plural-forms'=>'nplurals=2; plural=(n != 1);','language'=>'en','pot-creation-date'=>'2026-02-05 13:05+0200','po-revision-date'=>'2026-02-05 13:06+0200','translation-revision-date'=>'2026-02-05 13:06+0200','project-id-version'=>'RSFirewall!','x-generator'=>'Poedit 3.8','messages'=>[]];
